Ingeneo.AppContratos/Ingeneo.AppContratos/Controllers/NotificationController.cs
using Ingeneo.AppContratos.Models;
using Ingeneo.AppContratos.ModelViews;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace Ingeneo.AppContratos.Controllers
{
    public class NotificationController : Controller
    {
        private GestorContratosDbContext db = new GestorContratosDbContext();
        public DateTime FirstN = DateTime.Today.AddDays(10);        
        public DateTime SecN = DateTime.Today.AddDays(5);

        // GET: Notification
        public ActionResult Index()
        {
            return View();
        }
    }
}

Ingeneo.AppContratos/Ingeneo.AppContratos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ingeneo Contratos</title>    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr") 
    @*@Scripts.Render("~/bundles/pushN")*@    

    @*<script src="~/Scripts/push.min.js"></script>*@        
   
</head>
<body>   
    <div class="navbar navbar-inverse navbar-fixed-top">              
        <div class="container">
            <div class="navbar-header">
                <span style="float:left; margin-right:20px; margin-top:5px; margin-bottom:5px;"><img src="~/fonts/icon.png"/></span>               
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                 @Html.ActionLink("Menú Principal", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })                               
             </div>          
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin") || User.IsInRole("Monitor") || User.IsInRole("Analista"))
                            {
                                <a href="/Clientes/Index"><span class="glyphicon glyphicon-user"></span> Clientes</a>
                          }
                      }
                    </li>
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin") || User.IsInRole("Monitor") || User.IsInRole("Analista"))
                            {
                                <a href="/Contratos/Index"><span class="glyphicon glyphicon-briefcase"></span> Contratos</a>
                            }
                        }
                    </li>
                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin"))
                            {
                                <a href="/Users/Index"><span class="glyphicon glyphicon-cog"></span> Administración</a>                          
                            }
                        }
                    </li>

                    <li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            if (User.IsInRole("Admin") || User.IsInRole("Monitor") || User.IsInRole("Analista"))
                            {                                
                                <a href="/Notification/Index"><span class="glyphicon glyphicon-bell"></span></a>
                                @*@Html.ActionLink("Notify", "Index", "Notification", new { area = "" }, new { @class = "navbar-brand" })*@
                            }
                        }
                    </li>

                </ul>      
        @Html.Partial("_LoginPartial")
        </div>
      </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - <a href="http://www.ingeneo.com.co/index.php?lang=es">Ingeneo S.A.S</a> - Gestión de Contratos.</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval") 
    @Scripts.Render("~/bundles/datatables")   
    @Scripts.Render("~/bundles/bootstrap")      
    @Scripts.Render("~/bundles/Tool") 
      
    @RenderSection("scripts", required: false)
</body>
</html>