Ingeneo.AppContratos/Ingeneo.AppContratos/Controllers/ContratosController.cs
using System;
using System.Collections;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Ingeneo.AppContratos.Models;
using Ingeneo.AppContratos.ModelViews;
using System.Collections.Generic;

namespace Ingeneo.AppContratos.Controllers
{
    public class ContratosController : Controller
    {        
        private GestorContratosDbContext db = new GestorContratosDbContext();
        public DateTime FirstN = DateTime.Today.AddDays(10);
        public DateTime SecondN = DateTime.Today.AddDays(5);

        public class CustomAuth : AuthorizeAttribute
        {
            public string RedirectUrl = "/Account/Login";
            public override void OnAuthorization(AuthorizationContext filterContext)
            {
                base.OnAuthorization(filterContext);
                if (!filterContext.HttpContext.User.Identity.IsAuthenticated)
                {
                    filterContext.Result = new RedirectResult(RedirectUrl);
                    return;
                }
                if (filterContext.Result is HttpUnauthorizedResult)
                {
                    //Descomentar esta linea para usar JS alert enves de redireccionar a otro pagina
                    //filterContext.Result = new ContentResult { ContentType = "text/html", Content = "<script>alert('MAMBRU SE FUE A LA GUERRA!!! :@');window.location.href ='/Home/Index';</script> " };
                    
                    filterContext.Result = new RedirectResult("/Home/Denied");
                    return;
                }
            }
        }
        // GET: Contratos
        [CustomAuth(Roles = "Analista, Monitor, Admin")]
        public ActionResult Index(string pNombre)
        {
            string contr = pNombre;
            if (contr == "Inactivos")
            {
                var contrato = db.Contrato.Where(c => c.EstadoContrato == true);
                ViewData["valor"] = "inactivos";

                
                var contratosN = db.Contrato.ToList();
                var contratosNView = new List<Notification>();
                foreach (var cont in contratosN)
                {
                    if (cont.FechaFinContrato.HasValue)
                    {
                        var DateN = cont.FechaFinContrato.Value;
                        if (FirstN.Year == DateN.Year)
                        {
                            if (FirstN.Month == DateN.Month)
                            {
                                if (FirstN.Day == DateN.Day)
                                {                                   
                                    ViewBag.azul = true;
                                }
                            }
                        }
                    }
                }               

                foreach (var cont in contratosN)
                {
                    if (cont.FechaFinContrato.HasValue)
                    {
                        var DateN = cont.FechaFinContrato.Value;
                        if (SecondN.Year == DateN.Year)
                        {
                            if (SecondN.Month == DateN.Month)
                            {
                                if (SecondN.Day == DateN.Day)
                                {
                                    ViewBag.x = true;
                                }
                            }
                        }
                    }
                }
                return View(contrato.ToList());

            }
            else {
                var contrato = db.Contrato.Where(c => c.EstadoContrato == false);               
                ViewData["valor"] = "activos";

                if (true)
                {

                }

                var contratosN = db.Contrato.ToList();
                var contratosNView = new List<Notification>();
                foreach (var cont in contratosN)
                {
                    if (cont.FechaFinContrato.HasValue)
                    {
                        var DateN = cont.FechaFinContrato.Value;
                        if (FirstN.Year == DateN.Year || SecondN.Year == DateN.Year)
                        {
                            if (FirstN.Month == DateN.Month || SecondN.Month == DateN.Month)
                            {
                                if (FirstN.Day == DateN.Day || SecondN.Day == DateN.Day)
                                {
                                    ViewBag.blue = true;
                                }
                            }
                        }
                    }
                }

                var prorrogas = db.Prorroga.ToList();
                foreach (var pro in prorrogas)
                {
                    if (pro.FechaFinProrroga.HasValue)
                    {
                        var DateN = pro.FechaFinProrroga.Value;
                        if (FirstN.Year == DateN.Year || SecondN.Year == DateN.Year)
                        {
                            if (FirstN.Month == DateN.Month || SecondN.Month == DateN.Month)
                            {
                                if (FirstN.Day == DateN.Day || SecondN.Day == DateN.Day)
                                {
                                    ViewBag.green = true;
                                }
                            }
                        }
                    }
                }

                var polizas = db.Poliza.ToList();
                foreach (var pol in polizas)
                {
                    if (pol.FechaFinpoliza != null)
                    {
                        var DateN = pol.FechaFinpoliza;
                        if (FirstN.Year == DateN.Year || SecondN.Year == DateN.Year)
                        {
                            if (FirstN.Month == DateN.Month || SecondN.Month == DateN.Month)
                            {
                                if (FirstN.Day == DateN.Day || SecondN.Day == DateN.Day)
                                {
                                    ViewBag.yellow = true;
                                }
                            }
                        }
                    }
                }                
                return View(contrato.OrderBy(x => x.Cliente.NombreCliente).ToList());                
            }         
        }


        // GET: Contratos/Details/5
        [CustomAuth(Roles = "Analista, Monitor, Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                
                string hh = Url.Content("~/Content/sweetalert2.min.css");
                return Content("<link href='" + hh + "' rel='stylesheet' type='text/css'/>" +
                               "<script src='/Scripts/sweetalert2.min.js'></script>." +
                               "<Script>swal({title: 'Petición incorrecta al servidor..'," +
                               "text: 'El detalle del contrato que busca no existe en la base de datos, debes intentarlo de nuevo.'," +
                               "type: 'error'," +
                               "showCancelButton: false," +
                               "confirmButtonColor: '#3085d6'," +
                               "cancelButtonColor: '#d33'," +
                               "confirmButtonText: 'Aceptar!'}).then(function() " +
                               "{swal(''," +
                               "''," +
                               "'success', window.location.href='/Contratos/Index')});</script>");
            }
            Contrato contrato = db.Contrato.Find(id);
            
            if (contrato == null)
            {
                
                string hh = Url.Content("~/Content/sweetalert2.min.css");
                return Content("<link href='" + hh + "' rel='stylesheet' type='text/css'/>" +
                               "<script src='/Scripts/sweetalert2.min.js'></script>." +
                               "<Script>swal({title: 'El directorio especificado no existe en el servidor web..'," +
                               "text: 'Se ha quitado el recurso que está buscando, se le ha cambiado el nombre o no está disponible en estos momentos.'," +
                               "type: 'error'," +
                               "showCancelButton: false," +
                               "confirmButtonColor: '#3085d6'," +
                               "cancelButtonColor: '#d33'," +
                               "confirmButtonText: 'Aceptar!'}).then(function() " +
                               "{swal(''," +
                               "''," +
                               "'success', window.location.href='/Contratos/Index')});</script>");
            }
            return View(contrato);
        }

        // GET: Contratos/Create
        [CustomAuth(Roles = "Monitor, Admin, Analista")]
        public ActionResult Create()
        {
            //ViewBag.Clienteid = new SelectList(db.Cliente, "id", "NombreCliente");
            ViewBag.Clienteid = new SelectList(db.Cliente.OrderBy(x => x.NombreCliente), "id", "NombreCliente");
            return View();
        }

        // POST: Contratos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,CodigoContrato,FechaInicioContrato,FechaFinContrato,Clienteid,ValorContrato,EstadoContrato")] Contrato contrato)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var RepeatName = db.Contrato.Where(x => x.Clienteid == contrato.Clienteid && x.CodigoContrato == contrato.CodigoContrato).FirstOrDefault();

                    if (RepeatName == null)
                    {

Ingeneo.AppContratos/Ingeneo.AppContratos/Views/PolizasProrroga/Create.cshtml
@model Ingeneo.AppContratos.Models.Poliza

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm(null, null, FormMethod.Post, new
{
    id = "SavePolicyExtensionForm"
}))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h2>Crear Póliza</h2>
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CodigoPoliza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoPoliza, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoPoliza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NombreAseguradora, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreAseguradora, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreAseguradora, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaInicioPoliza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class='input-group date' id='datetimepicker6' style="width:280px">
                    @Html.EditorFor(model => model.FechaInicioPoliza, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.FechaInicioPoliza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaFinpoliza, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class='input-group date' id='datetimepicker7' style="width:280px">
                    @Html.EditorFor(model => model.FechaFinpoliza, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.FechaFinpoliza, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">               
                @Html.Hidden("idProrroga", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="btnCreate" value="Guardar" onclick="Validate(this, event);" class="btn btn-success" />               
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-primary" href="/Contratos/Index"><span class="glyphicon glyphicon-home"></span> Regresar a contratos</a>
</div>
@section Scripts {

    @Scripts.Render("~/Scripts/validatePolicyExtension.js")
}

Ingeneo.AppContratos/Ingeneo.AppContratos/Views/PolizasProrroga/Details.cshtml
@model Ingeneo.AppContratos.Models.Prorroga

@{
    ViewBag.Title = "Detalles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h2>Detalles póliza y coberturas de la prórroga</h2>
    <hr />
    <table class="table table-striped table-hover table-responsive table-bordered">
        <thead>
            <tr>
                <th>
                    Nombre del cliente
                </th>
                <th>
                    Nombre del contrato
                </th>
                <th>
                    Código de la póliza
                </th>
                <th>
                    Nombre de la aseguradora
                </th>
                <th>
                    Fecha inicio de la póliza
                </th>
                <th>
                    Fecha fin de la póliza
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model.PolizaPro)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => model.Contrato.Cliente.NombreCliente)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Contrato.CodigoContrato)
                    </td>
                    <td>
                        @x.CodigoPoliza
                    </td>
                    <td>
                        @x.NombreAseguradora
                    </td>
                    <td>
                        @x.FechaInicioPoliza.ToShortDateString()
                    </td>
                    <td>
                        @x.FechaFinpoliza.ToShortDateString()
                    </td>
                    <td>
                        <a class="btn btn-warning" data-toggle="tooltip" title="Editar póliza" href="/Polizas/Edit/@x.id"> <span class="glyphicon glyphicon-edit"></span></a>
                        <a class="btn btn-danger" data-toggle="tooltip" title="Borrar póliza" href="/Polizas/Delete/@x.id"><span class="glyphicon glyphicon-trash"></span></a> 
                        <a class="btn btn-info" data-toggle="tooltip" title="Agregar Cobertura" href="/DetallePolizas/Create/@x.id"> <span class="glyphicon glyphicon-plus"></span></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <hr />
    <br />
    <table class="table table-striped table-hover table-responsive table-bordered">
        <thead>
            <tr><th colspan="5" style="text-align:center; font-weight:bold">Coberturas de la poliza</th></tr>
            <tr>
                <th>
                    Descripcion de la cobertura
                </th>
                <th>
                    Fecha Inicio Cobertura
                </th>
                <th>
                    Fecha Fin Cobertura
                </th>
                <th>

                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model.PolizaPro)
            {
                foreach (var z in x.DetallePoliza)
                {
                    <tr>
                        <td>
                            @z.DescripcionCobertura
                        </td>
                        <td>
                            @z.FechaInicioProteccion.ToShortDateString()
                        </td>
                        <td>
                            @z.FechaFinProteccion.ToShortDateString()
                        </td>
                        <td>
                            <a class="btn btn-warning" data-toggle="tooltip" title="Editar cobertura" href="/DetallePolizas/Edit/@z.id"> <span class="glyphicon glyphicon-edit"></span></a>
                            <a class="btn btn-danger" data-toggle="tooltip" title="Borrar" href="/DetallePolizas/Delete/@z.id"><span class="glyphicon glyphicon-trash"></span></a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<p>

    <a class="btn btn-primary" href=@Url.Action("Details", "Contratos", new { id = Model.Contratoid })><span class="glyphicon glyphicon-arrow-left"></span>  Regresar a prórrogas</a>
  
</p>